databases:
  - name: private-events
    databaseName: private-events
    user: private-events
    plan: free

services:
  - type: web
    name: private-events
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: private-events
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
